language: ruby
rvm:
  - 2.2.4
before_install: gem install bundler -v 1.11.2
script: 'bundle exec rake'
notifications:
  email:
    recipients:
      - joshaidan@gmail.com
    on_failure: change
    on_success: never
addons:
    code_climate:
        repo_token: fc2cbe7a049ca00aba0075114c2c40ff3f328fbe98a98cf3cda61758c4efdce6
