language: ruby
rvm:
  - 2.2.4
before_install: gem install bundler -v 1.11.2
script: 'bundle exec rake'
notifications:
  email:
    recipients:
      - joshaidan@gmail.com
    on_failure: change
    on_success: never